/*
 * Customer Offer
 * This service domain orchestrates the processing of a product offer for a new or established &nbsp;customer. The offer process is defined specifically for the product or service being considered and can include actions such as document checks, collateral allocation, credit assessments, underwriting decisions, regulatory and procedural checks, eligibility checks, the use of internal and external specialist services (such as evaluations and legal advice).
 *
 * OpenAPI spec version: 10.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.hsbc.hbar.mdw.customeroffer.model;

import java.util.Objects;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Transient;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * CustomerOfferProcedure
 */

@Entity
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-05-25T00:52:16.353Z[GMT]")
public class CustomerOfferProcedure {
	
  @Id
  @GeneratedValue(strategy=GenerationType.IDENTITY)
  private Long id;
  
  @Transient
  @SerializedName("CustomerReference")
  private Object customerReference = null;

  @Transient
  @SerializedName("PartyReference")
  private Object partyReference = null;

  @SerializedName("ProductandServiceType")
  private String productandServiceType = null;

  @SerializedName("CustomerOfferProcessingSchedule")
  private String customerOfferProcessingSchedule = null;

  @SerializedName("CustomerOfferProcessingTask")
  private String customerOfferProcessingTask = null;

  @SerializedName("CustomerOfferProcessingTaskType")
  private String customerOfferProcessingTaskType = null;

  @Transient
  @SerializedName("EmployeeOrBusinessUnitReference")
  private Object employeeOrBusinessUnitReference = null;

  @SerializedName("CustomerOfferProcessingTaskWorkProducts")
  private String customerOfferProcessingTaskWorkProducts = null;

  @SerializedName("CustomerOfferProcessingTaskResult")
  private String customerOfferProcessingTaskResult = null;

  public CustomerOfferProcedure customerReference(Object customerReference) {
    this.customerReference = customerReference;
    return this;
  }

   /**
   * Get customerReference
   * @return customerReference
  **/
  @Schema(description = "")
  public Object getCustomerReference() {
    return customerReference;
  }

  public void setCustomerReference(Object customerReference) {
    this.customerReference = customerReference;
  }

  public CustomerOfferProcedure partyReference(Object partyReference) {
    this.partyReference = partyReference;
    return this;
  }

   /**
   * Get partyReference
   * @return partyReference
  **/
  @Schema(description = "")
  public Object getPartyReference() {
    return partyReference;
  }

  public void setPartyReference(Object partyReference) {
    this.partyReference = partyReference;
  }

  public CustomerOfferProcedure productandServiceType(String productandServiceType) {
    this.productandServiceType = productandServiceType;
    return this;
  }

   /**
   * Get productandServiceType
   * @return productandServiceType
  **/
  @Schema(description = "")
  public String getProductandServiceType() {
    return productandServiceType;
  }

  public void setProductandServiceType(String productandServiceType) {
    this.productandServiceType = productandServiceType;
  }

  public CustomerOfferProcedure customerOfferProcessingSchedule(String customerOfferProcessingSchedule) {
    this.customerOfferProcessingSchedule = customerOfferProcessingSchedule;
    return this;
  }

   /**
   * Get customerOfferProcessingSchedule
   * @return customerOfferProcessingSchedule
  **/
  @Schema(description = "")
  public String getCustomerOfferProcessingSchedule() {
    return customerOfferProcessingSchedule;
  }

  public void setCustomerOfferProcessingSchedule(String customerOfferProcessingSchedule) {
    this.customerOfferProcessingSchedule = customerOfferProcessingSchedule;
  }

  public CustomerOfferProcedure customerOfferProcessingTask(String customerOfferProcessingTask) {
    this.customerOfferProcessingTask = customerOfferProcessingTask;
    return this;
  }

   /**
   * Get customerOfferProcessingTask
   * @return customerOfferProcessingTask
  **/
  @Schema(description = "")
  public String getCustomerOfferProcessingTask() {
    return customerOfferProcessingTask;
  }

  public void setCustomerOfferProcessingTask(String customerOfferProcessingTask) {
    this.customerOfferProcessingTask = customerOfferProcessingTask;
  }

  public CustomerOfferProcedure customerOfferProcessingTaskType(String customerOfferProcessingTaskType) {
    this.customerOfferProcessingTaskType = customerOfferProcessingTaskType;
    return this;
  }

   /**
   * Get customerOfferProcessingTaskType
   * @return customerOfferProcessingTaskType
  **/
  @Schema(description = "")
  public String getCustomerOfferProcessingTaskType() {
    return customerOfferProcessingTaskType;
  }

  public void setCustomerOfferProcessingTaskType(String customerOfferProcessingTaskType) {
    this.customerOfferProcessingTaskType = customerOfferProcessingTaskType;
  }

  public CustomerOfferProcedure employeeOrBusinessUnitReference(Object employeeOrBusinessUnitReference) {
    this.employeeOrBusinessUnitReference = employeeOrBusinessUnitReference;
    return this;
  }

   /**
   * Get employeeOrBusinessUnitReference
   * @return employeeOrBusinessUnitReference
  **/
  @Schema(description = "")
  public Object getEmployeeOrBusinessUnitReference() {
    return employeeOrBusinessUnitReference;
  }

  public void setEmployeeOrBusinessUnitReference(Object employeeOrBusinessUnitReference) {
    this.employeeOrBusinessUnitReference = employeeOrBusinessUnitReference;
  }

  public CustomerOfferProcedure customerOfferProcessingTaskWorkProducts(String customerOfferProcessingTaskWorkProducts) {
    this.customerOfferProcessingTaskWorkProducts = customerOfferProcessingTaskWorkProducts;
    return this;
  }

   /**
   * Get customerOfferProcessingTaskWorkProducts
   * @return customerOfferProcessingTaskWorkProducts
  **/
  @Schema(description = "")
  public String getCustomerOfferProcessingTaskWorkProducts() {
    return customerOfferProcessingTaskWorkProducts;
  }

  public void setCustomerOfferProcessingTaskWorkProducts(String customerOfferProcessingTaskWorkProducts) {
    this.customerOfferProcessingTaskWorkProducts = customerOfferProcessingTaskWorkProducts;
  }

  public CustomerOfferProcedure customerOfferProcessingTaskResult(String customerOfferProcessingTaskResult) {
    this.customerOfferProcessingTaskResult = customerOfferProcessingTaskResult;
    return this;
  }

   /**
   * Get customerOfferProcessingTaskResult
   * @return customerOfferProcessingTaskResult
  **/
  @Schema(description = "")
  public String getCustomerOfferProcessingTaskResult() {
    return customerOfferProcessingTaskResult;
  }

  public void setCustomerOfferProcessingTaskResult(String customerOfferProcessingTaskResult) {
    this.customerOfferProcessingTaskResult = customerOfferProcessingTaskResult;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerOfferProcedure customerOfferProcedure = (CustomerOfferProcedure) o;
    return Objects.equals(this.customerReference, customerOfferProcedure.customerReference) &&
        Objects.equals(this.partyReference, customerOfferProcedure.partyReference) &&
        Objects.equals(this.productandServiceType, customerOfferProcedure.productandServiceType) &&
        Objects.equals(this.customerOfferProcessingSchedule, customerOfferProcedure.customerOfferProcessingSchedule) &&
        Objects.equals(this.customerOfferProcessingTask, customerOfferProcedure.customerOfferProcessingTask) &&
        Objects.equals(this.customerOfferProcessingTaskType, customerOfferProcedure.customerOfferProcessingTaskType) &&
        Objects.equals(this.employeeOrBusinessUnitReference, customerOfferProcedure.employeeOrBusinessUnitReference) &&
        Objects.equals(this.customerOfferProcessingTaskWorkProducts, customerOfferProcedure.customerOfferProcessingTaskWorkProducts) &&
        Objects.equals(this.customerOfferProcessingTaskResult, customerOfferProcedure.customerOfferProcessingTaskResult);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerReference, partyReference, productandServiceType, customerOfferProcessingSchedule, customerOfferProcessingTask, customerOfferProcessingTaskType, employeeOrBusinessUnitReference, customerOfferProcessingTaskWorkProducts, customerOfferProcessingTaskResult);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerOfferProcedure {\n");
    
    sb.append("    customerReference: ").append(toIndentedString(customerReference)).append("\n");
    sb.append("    partyReference: ").append(toIndentedString(partyReference)).append("\n");
    sb.append("    productandServiceType: ").append(toIndentedString(productandServiceType)).append("\n");
    sb.append("    customerOfferProcessingSchedule: ").append(toIndentedString(customerOfferProcessingSchedule)).append("\n");
    sb.append("    customerOfferProcessingTask: ").append(toIndentedString(customerOfferProcessingTask)).append("\n");
    sb.append("    customerOfferProcessingTaskType: ").append(toIndentedString(customerOfferProcessingTaskType)).append("\n");
    sb.append("    employeeOrBusinessUnitReference: ").append(toIndentedString(employeeOrBusinessUnitReference)).append("\n");
    sb.append("    customerOfferProcessingTaskWorkProducts: ").append(toIndentedString(customerOfferProcessingTaskWorkProducts)).append("\n");
    sb.append("    customerOfferProcessingTaskResult: ").append(toIndentedString(customerOfferProcessingTaskResult)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
